### ISSUE TITLE
Task 1

### ISSUE THREAD

**Issue by Sri99182** [Sri99182/Project-S#1]
convert any data from .JSON or .CSV to bar graph

**Comment by Ranith184** [comment]
Task 1 finished

**Comment by Ranith184** [comment]
Task  1 finished

**Comment by Sri99182** [comment]
[Adverting.pdf](https://github.com/user-attachments/files/16929468/Adverting.pdf)

**Comment by Ranith184** [comment]
[Copy of piechart - Colab.pdf](https://github.com/user-attachments/files/16929583/Copy.of.piechart.-.Colab.pdf)

**Comment by Shivanireddy102** [comment]
[BarGraph.ipynb - Colab.pdf](https://github.com/user-attachments/files/17033129/BarGraph.ipynb.-.Colab.pdf)
Done.
