### ISSUE TITLE
convert dataset into pie chart

### ISSUE THREAD

**Issue by Sri99182** [Sri99182/Project-S#3]

**Comment by Shivanireddy102** [comment]
issues cleared

**Comment by Ranith184** [comment]
completed

**Comment by Ranith184** [comment]
[Copy of piechart - Colab.pdf](https://github.com/user-attachments/files/16929589/Copy.of.piechart.-.Colab.pdf)

**Comment by Shivanireddy102** [comment]
[piechart.ipynb - Colab.pdf](https://github.com/user-attachments/files/17033047/piechart.ipynb.-.Colab.pdf)
Done.
